### ISSUE TITLE
个人及商业使用授权问题

### ISSUE THREAD

**Issue by AIClaw4X** [viccowang/viccovlog-davinci-materials#3]
首先非常感谢Vicco提供这么棒的东西！
因为自己是做开源软件这一块的，所以对版权等问题比较敏感
请问关于个人（特别是使用这些素材工具制作的视频在上传视频网站后可能出现获利）和商业使用的授权及费用问题，能否在README里面提一下。谢谢！
（个人目前纯自制玩，帮大家问一下 😊)

**Comment by viccowang** [comment]
好的，我会在Readme部分补充一下版权问题。

**Comment by AIClaw4X** [comment]
看到版权申明了，谢谢
可以关掉这个issue了
